trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/
    exclude:
      - bicep/
pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'asphyticz/marvelo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)'